
name: Release package

on:
  push:
    tags:
      - "*"

jobs:
  publish-npm:
    name: Publish NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Tests
        run: npm test
        shell: bash

      - name: Publish
        run: npm publish
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
